### ISSUE TITLE
[UI] Can't view logs

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#799]
**To reproduce:**
1. Go [here](https://taskcluster-ui.herokuapp.com/tasks/F_B6duziT5iKZS9wFk4CWw/runs/0/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FF_B6duziT5iKZS9wFk4CWw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log)

> `r.n is not a function`

Nothing was printed in the console

**Comment by helfi92** [comment]
This was probably introduced in https://github.com/taskcluster/taskcluster/pull/793. The change has been reverted. The issue seems to happen in production only. I'll investigate.

**Comment by djmitche** [comment]
@helfi92 Is this relaeted to https://bugzilla.mozilla.org/show_bug.cgi?id=1555075 ?  I saw the same error message yesterday when web-server had crashed.

**Comment by helfi92** [comment]
I don't think so. I pushed a PR to fix Bug 1555075. Still need to investigate this issue.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/37c5098c9cdd5bf324b85a3ce3045a82d7f24944.
